/*CREACION DE TABLAS RECYCLON*/
DROP TABLE IF EXISTS COBROS;
DROP TABLE IF EXISTS PAGOS;
DROP TABLE IF EXISTS CLIENTES;
DROP TABLE IF EXISTS BANCOS; 
DROP TABLE IF EXISTS PROVEEDORES;


CREATE TABLE CLIENTES(
ID integer primary key identity(1,1),
NOMBRE VARCHAR(40) CONSTRAINT EMP_NOMBRE UNIQUE NOT NULL,
NCUENTA VARCHAR(24) CONSTRAINT EMP_CUENTA UNIQUE
);

CREATE TABLE PROVEEDORES(
ID integer primary key identity(1,1),
NOMBRE VARCHAR(40) CONSTRAINT PRO_NOMBRE UNIQUE NOT NULL
);

CREATE TABLE BANCOS(
ID integer primary key identity(1,1),
NOMBRE VARCHAR(40) CONSTRAINT BAN_NOMBRE UNIQUE NOT NULL
);

CREATE TABLE PAGOS(
ID integer primary key identity(1,1),
IDPROVEEDOR integer CONSTRAINT FK_IDPROV_PAGO REFERENCES PROVEEDORES,
IDBANCO integer CONSTRAINT FK_IDBAN_PAGO REFERENCES BANCOS,
IMPORTE float constraint IMPORTE_PAGOS NOT NULL,
NUMFACTURA integer,
FECHAVENCIMIENTO datetime,
FORMAPAGO VARCHAR(25),
ESTADO bit CONSTRAINT CHK_ESTADO_P CHECK (ESTADO IN(0,1))
);

CREATE TABLE COBROS(
ID integer primary key identity(1,1),
IDCLIENTE integer CONSTRAINT FK_IDCLI_COBRO REFERENCES CLIENTES,
IDBANCO integer CONSTRAINT FK_IDBAN_COBRO REFERENCES BANCOS,
IMPORTE float,
NUMFACTURA integer,
FECHA DATETIME,
FORMAPAGO VARCHAR(25),
ESTADO bit CONSTRAINT CHK_ESTADO_C CHECK (ESTADO IN(0,1))
);